import React from 'react';
import type { SummaryReport } from '../types.ts';
import { EyeIcon } from './IconComponents.tsx';

interface SummaryReportListProps {
    reports: SummaryReport[];
    onView: (report: SummaryReport) => void;
}

const SummaryReportList: React.FC<SummaryReportListProps> = ({ reports, onView }) => {
    if (reports.length === 0) {
        return (
            <div className="text-center text-gray-500 py-8 border-2 border-dashed rounded-lg">
                <p>No summary reports have been generated yet.</p>
                <p className="text-sm mt-1">Use the filters and click "Generate AI Summary" to create your first report.</p>
            </div>
        );
    }
    
    return (
        <div className="bg-white rounded-lg shadow-sm overflow-hidden">
            <table className="min-w-full divide-y divide-gray-200">
                <caption className="sr-only">List of generated summary reports.</caption>
                <thead className="bg-gray-50">
                    <tr>
                        <th scope="col" className="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">Report Title</th>
                        <th scope="col" className="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">Generated By</th>
                        <th scope="col" className="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">Date Generated</th>
                        <th scope="col" className="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">Actions</th>
                    </tr>
                </thead>
                <tbody className="bg-white divide-y divide-gray-200">
                    {reports.map((report) => (
                        <tr key={report.id} className="hover:bg-gray-50">
                            <th scope="row" className="px-6 py-4 whitespace-nowrap text-left font-medium">
                                <div className="text-sm text-gray-900">{report.title}</div>
                                <div className="text-sm text-gray-500 font-normal">{report.id}</div>
                            </th>
                            <td className="px-6 py-4 whitespace-nowrap text-sm text-gray-500">{report.generatedBy}</td>
                            <td className="px-6 py-4 whitespace-nowrap text-sm text-gray-500">{report.generatedDate}</td>
                            <td className="px-6 py-4 whitespace-nowrap text-sm font-medium">
                                <button onClick={() => onView(report)} aria-label={`View report ${report.title}`} className="text-gray-400 hover:text-atlas-blue rounded-md focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-atlas-blue" title="View Report">
                                    <EyeIcon className="h-5 w-5"/>
                                </button>
                            </td>
                        </tr>
                    ))}
                </tbody>
            </table>
        </div>
    );
};

export default SummaryReportList;
